---
- hosts: localhost
  remote_user: root
  vars:
    download_url: http://10.252.226.123:18081/repository/raw-hosted/jdk-8u231-linux-x64.tar.gz
    download_folder: /opt
    java_name: "{{download_folder}}/jdk1.8.0_231"
    java_archive: "{{download_folder}}/jdk-8u231-linux-x64.tar.gz"


  tasks:
  - name: Download Java
    command: "wget -q -O {{java_archive}} {{download_url}} creates={{java_archive}}"

  - name: Unpack archive
    command: "tar -zxf {{java_archive}} -C {{download_folder}} creates={{java_name}}"

  - name: Fix ownership
    file: state=directory path={{java_name}} owner=root group=root recurse=yes

  - name: Make Java available for system
    command: 'alternatives --install "/usr/bin/java" "java" "{{java_name}}/bin/java" 2000'

  - name: Clean up
    file: state=absent path={{java_archive}}
